name: otter-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - nb_conda_kernels
  - pip:
      - datascience
      - jupyter_client
      - ipykernel
      - matplotlib
      - pandas
      - ipywidgets
      - scipy
      - seaborn
      - scikit-learn
      - jinja2
      - nbconvert
      - nbformat
      - dill
      - numpy
      - gspread
      - pypdf
      - otter-grader[export,grading,plugins]==5.6.0
